name: exercicio_imc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-196.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router: ^6.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/